# nginx proxy address - http://172.17.0.1:7777

name: hastebin
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: ghcr.io/toptal/haste-server:latest
    pull_policy: always
    container_name: hastebin-app
    restart: always
    logging: *default-logging
    networks:
      - hastebin
      - proxy
      - cloudflare
    ports:
      - "172.17.0.1:7777:7777"
    environment:
      TZ: ${TZ:-America/New_York}
      STORAGE_TYPE: ${HASTEBIN_STORAGE:-redis}
      STORAGE_HOST: hastebin-redis
      STORAGE_PORT: 6379
      STORAGE_DB: 2
      STORAGE_EXPIRE_SECONDS: ${HASTEBIN_EXPIRE:-2592000}
      CONTAINER_NAME: hastebin-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    depends_on:
      - hastebin-redis
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://hastebin-app:7777'
      - 'cloudflare.hostname=hastebin.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.hastebin-app.entrypoints=http'
      - 'traefik.http.routers.hastebin-app-secure.tls=true'
      - 'traefik.http.routers.hastebin-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.hastebin-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.hastebin-app.middlewares=hastebin-app-https-redirect'
      - 'traefik.http.routers.hastebin-app-secure.entrypoints=https'
      - 'traefik.http.routers.hastebin-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.hastebin-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.hastebin-app-secure.service=hastebin-app'
      - 'traefik.http.services.hastebin-app.loadbalancer.server.port=7777'

  hastebin-redis:
    image: redis:alpine
    pull_policy: always
    container_name: hastebin-redis
    restart: always
    logging: *default-logging
    networks:
      - hastebin
    volumes:
      - ./volumes/data/redis/hastebin:/data
    environment:
      CONTAINER_NAME: hastebin-redis

networks:
  hastebin:
    name: hastebin
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
